### ISSUE TITLE
Fails on sites with a prefix

### ISSUE THREAD

**Issue by Blake-** [duspeccoll/next_accession#1]
Howdy, this doesn't seem to work on a site running on a prefix. So, for example, I run it on example.com/staff/  and go to the plugin page, it gives me a bad 404 URL on example.com/plugins/next_accession

**Comment by jackflaps** [comment]
I have a fix for this that appears to work (it's just https://github.com/hudmol/digitization_work_order/blob/master/frontend/routes.rb). Can submit a PR tomorrow.

**Comment by jackflaps** [comment]
Resolved by https://github.com/duspeccoll/next_accession/pull/2.
